from pathlib import Path
from datetime import datetime
from urllib.parse import urlparse


class ReportManager:
    """
    Handles saving analysis reports generated by the application.
    """

    def __init__(self):
        self.project_root = Path(__file__).resolve().parent.parent

        # reports/deephat/
        self.deephat_dir = self.project_root / "reports" / "deephat"
        self.deephat_dir.mkdir(parents=True, exist_ok=True)

    def _target_name(self, target: str) -> str:
        """
        Convert a URL into a filesystem-safe name.
        """

        parsed = urlparse(target)

        host = parsed.netloc.replace(":", "_")

        if not host:
            host = "unknown_target"

        return host

    def save_deephat_report(self, target: str, response: str) -> Path:
        """
        Save the raw DeepHat response as a Markdown file.
        """

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        filename = (
            f"deephat_{self._target_name(target)}_{timestamp}.md"
        )

        report_path = self.deephat_dir / filename

        report_path.write_text(response, encoding="utf-8")

        print(f"\n[+] DeepHat report saved:")
        print(report_path)

        return report_path