from pathlib import Path
from datetime import datetime
from urllib.parse import urlparse
import json


class ReportManager:
    """
    Handles saving analysis reports generated by the application.

    Each scan runs a different subset of agents depending on what DeepHat
    actually routed for that specific target — one scan might run
    AUTHZ_AGENT + PASSWORD_POLICY_AGENT, another might run SQL_AGENT +
    XSS_AGENT, another might run nothing at all. generate_combined_report()
    reflects that: it builds ONE final report per scan containing DeepHat's
    candidate analysis, a summary table of every agent that ran, and then
    a full detailed section for each one — using per-agent formatting,
    since every agent wrapper returns a completely different result shape
    (there's no single schema across XSS/AUTHZ/PASSWORD_POLICY/
    SOURCE_AUDIT/MITM/NOSQL/SQL — each underlying tool was never designed
    to share one). Only agents that actually appear in agent_results for
    THIS scan get a section; nothing is padded in for agents that didn't
    run.
    """

    def __init__(self):
        self.project_root = Path(__file__).resolve().parent.parent

        # reports/deephat/
        self.deephat_dir = self.project_root / "reports" / "deephat"
        self.deephat_dir.mkdir(parents=True, exist_ok=True)

    def _target_name(self, target: str) -> str:
        """
        Convert a URL into a filesystem-safe name.
        """

        parsed = urlparse(target)

        host = parsed.netloc.replace(":", "_")

        if not host:
            host = "unknown_target"

        return host

    # -----------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------

    def save_deephat_report(self, target: str, response: str) -> Path:
        """
        Backward-compatible: saves just DeepHat's raw candidate JSON with
        no agent detail. Prefer generate_combined_report() — this is kept
        only in case something else still calls it directly.
        """
        return self._write_report(target, response)

    def generate_combined_report(self, target: str, deephat_response: str,
                                  agent_results: list) -> Path:
        """
        Build and save the single combined final report for one scan:
        DeepHat's candidate analysis + a summary table + a full detailed
        section per agent that actually ran.

        Args:
            target:           The scanned URL.
            deephat_response: DeepHat's raw JSON text (as produced by the
                               model, already validated by OutputParser).
            agent_results:    The list of {agent, status, result/error}
                               dicts Executor.execute() returned for this
                               scan — whatever subset of agents actually
                               ran, in whatever order they ran.
        """

        sections = []

        sections.append(self._format_header(target))
        sections.append(self._format_deephat_section(deephat_response))
        sections.append(self._format_summary_table(agent_results))

        if agent_results:
            for result in agent_results:
                sections.append(self._format_agent_section(result))
        else:
            sections.append(
                "\n## Agent Results\n\nNo validation agents were executed "
                "for this scan — DeepHat found no candidates worth routing, "
                "or every candidate was rejected by the grounding/safety "
                "checks before reaching an agent.\n"
            )

        combined = "\n".join(sections)

        return self._write_report(target, combined)

    # -----------------------------------------------------------------
    # Internal — assembly
    # -----------------------------------------------------------------

    def _write_report(self, target: str, content: str) -> Path:
        # No timestamp: same target always writes to the same path, so a
        # new scan replaces the previous report for that target rather
        # than accumulating a new file every run. If you want history
        # across runs, that's what reports/spiders/ + this file's git
        # history (if version-controlled) are for -- this is meant to be
        # "the current report for this target", not an archive.
        filename = f"deephat_{self._target_name(target)}.md"

        report_path = self.deephat_dir / filename

        report_path.write_text(content, encoding="utf-8")

        print(f"\n[+] Combined report saved:")
        print(report_path)

        return report_path

    def _format_header(self, target: str) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return (
            f"# DeepHat Security Report\n\n"
            f"**Target:** {target}\n\n"
            f"**Generated:** {now}\n\n"
            f"---\n"
        )

    def _format_deephat_section(self, deephat_response: str) -> str:
        lines = ["\n## DeepHat Candidate Analysis\n"]

        try:
            data = json.loads(deephat_response)
        except (json.JSONDecodeError, TypeError):
            # Fall back to showing the raw text if it isn't (or is no
            # longer, after retries/repairs) valid JSON for some reason.
            lines.append("```json")
            lines.append(str(deephat_response))
            lines.append("```")
            return "\n".join(lines)

        summary = data.get("summary", {})
        lines.append(
            f"**Total candidates:** {summary.get('total_candidates', 0)} "
            f"(critical={summary.get('critical', 0)}, "
            f"high={summary.get('high', 0)}, "
            f"medium={summary.get('medium', 0)}, "
            f"low={summary.get('low', 0)}, "
            f"informational={summary.get('informational', 0)})\n"
        )

        candidates = data.get("candidates", [])
        if not candidates:
            lines.append("_No candidates proposed for this scan._")
            return "\n".join(lines)

        for cand in candidates:
            lines.append(f"### {cand.get('finding_id', '?')} — {cand.get('type', 'unknown')}")
            lines.append(f"- **Endpoint:** {cand.get('endpoint') or '_(site-wide)_'}")
            lines.append(f"- **Method:** {cand.get('method') or 'N/A'}")
            lines.append(f"- **Severity:** {cand.get('severity', 'N/A')}  |  **Confidence:** {cand.get('confidence', 'N/A')}")
            lines.append(f"- **Status:** {cand.get('status', 'N/A')}")
            lines.append(f"- **Recommended agent:** {cand.get('recommended_agent') or '_none — no matching agent_'}")
            lines.append(f"- **Reasoning:** {cand.get('reasoning', 'N/A')}")
            evidence = cand.get("evidence") or []
            if evidence:
                lines.append(f"- **Evidence:** {', '.join(str(e) for e in evidence)}")
            lines.append("")

        return "\n".join(lines)

    def _format_summary_table(self, agent_results: list) -> str:
        lines = ["\n## Agent Summary\n"]

        if not agent_results:
            lines.append("_No agents ran for this scan._")
            return "\n".join(lines)

        lines.append("| Agent | Status | Total | Confirmed |")
        lines.append("|---|---|---|---|")

        for result in agent_results:
            agent_name = result.get("agent", "?")
            status = result.get("status", "?")

            if status == "SUCCESS":
                total, confirmed = self._extract_counts(agent_name, result.get("result") or {})
                lines.append(f"| {agent_name} | {status} | {total} | {confirmed} |")
            else:
                lines.append(f"| {agent_name} | {status} | — | — |")

        return "\n".join(lines)

    def _format_agent_section(self, result: dict) -> str:
        agent_name = result.get("agent", "UNKNOWN_AGENT")
        status = result.get("status", "UNKNOWN")

        lines = [f"\n---\n\n## {agent_name} — Detailed Report\n"]
        lines.append(f"**Status:** {status}\n")

        if status == "FAILED":
            lines.append(f"**Error:** {result.get('error', 'unknown error')}\n")
            return "\n".join(lines)

        if status in ("SKIPPED", "NOT_IMPLEMENTED"):
            inner = result.get("result")

            if isinstance(inner, dict) and "candidates" in inner:
                # UNSUPPORTED/SKIPPED buckets: "agent_name" here is
                # actually the bucket, and inner["candidates"] is the
                # real list of individual candidates that landed here,
                # each with its own reason.
                candidates = inner.get("candidates", [])
                lines.append(f"**{len(candidates)} candidate(s):**\n")
                for c in candidates:
                    lines.append(f"- `{c.get('finding_id')}` → `{c.get('endpoint')}`")
                    lines.append(f"  - Reason: {c.get('reason')}")
                return "\n".join(lines)

            reason = inner.get("reason") if isinstance(inner, dict) else None
            if reason:
                lines.append(f"**Reason:** {reason}\n")
            return "\n".join(lines)

        agent_result = result.get("result") or {}

        formatter = self._AGENT_FORMATTERS.get(agent_name, ReportManager._format_generic)
        lines.append(formatter(self, agent_result))

        return "\n".join(lines)

    # -----------------------------------------------------------------
    # Internal — per-agent counting (mirrors chat.py's
    # _extract_finding_counts; kept in sync deliberately, see note below)
    # -----------------------------------------------------------------

    def _extract_counts(self, agent_name, agent_result):
        """
        Same logic as chat.py's _extract_finding_counts(). Duplicated
        rather than imported to keep report_manager.py import-independent
        of chat.py (chat.py is the entry point, not a library module) —
        if you change one, change the other. Each agent wrapper returns a
        different result shape; there's no single "total/confirmed" key
        pair that works across all of them.
        """
        if not isinstance(agent_result, dict):
            return 0, 0

        if agent_name == "AUTHZ_AGENT":
            # AuthzWrapper's real return shape is flat (results/
            # total_results/total_vulnerabilities) — there is no nested
            # "summary" key. confirmed_count is written by Executor's
            # AUTHZ_AGENT branch; fall back to recomputing from results
            # directly in case this runs on an older/raw result.
            total = agent_result.get("total_results", len(agent_result.get("results", [])))
            confirmed = agent_result.get("confirmed_count")
            if confirmed is None:
                confirmed = sum(
                    1 for r in agent_result.get("results", [])
                    if r.get("finding") in ("VULNERABLE", "LIKELY_VULNERABLE")
                )
            return total, confirmed

        if agent_name in ("NOSQL_AGENT", "SQL_AGENT", "PARAM_INJECTION_AGENT"):
            summary = agent_result.get("summary", {})
            total = summary.get("vulnerabilities_found",
                                 summary.get("total_tests", len(agent_result.get("findings", []))))
            confirmed = summary.get("confirmed", summary.get("critical", 0) + summary.get("high", 0))
            return total, confirmed

        if agent_name == "PASSWORD_POLICY_AGENT":
            if agent_result.get("gap_reason"):
                return 0, 0
            severity_obj = agent_result.get("severity")
            label = ""
            if isinstance(severity_obj, dict):
                label = str(severity_obj.get("label", "")).upper()
            elif isinstance(severity_obj, str):
                label = severity_obj.upper()
            is_weak = label in ("CRITICAL", "WEAK", "MODERATE")
            return (1, 1) if is_weak else (0, 0)

        findings = agent_result.get("findings", [])
        total = len(findings) if isinstance(findings, list) else 0
        return total, total

    # -----------------------------------------------------------------
    # Internal — per-agent detailed formatting
    # -----------------------------------------------------------------

    def _format_xss(self, r: dict) -> str:
        findings = r.get("findings", [])
        if not findings:
            return "_No confirmed XSS findings._"
        out = [f"**{len(findings)} confirmed finding(s)** (browser dialog-confirmed only):\n"]
        for f in findings:
            out.append(f"- **[{f.get('xss_type', '?')}]** `{f.get('url', '?')}`")
            out.append(f"  - Parameter: `{f.get('param', '?')}`  |  Context: {f.get('context', '?')}")
            out.append(f"  - Payload: `{f.get('payload', '?')}`")
            out.append(f"  - Confidence: {f.get('confidence_score', f.get('confidence', '?'))}")
            if f.get("screenshot"):
                out.append(f"  - Screenshot: `{f.get('screenshot')}`")
        return "\n".join(out)

    def _format_authz(self, r: dict) -> str:
        total = r.get("total_results", len(r.get("results", [])))
        vulnerable = [
            res for res in r.get("results", [])
            if isinstance(res, dict) and res.get("finding") in ("VULNERABLE", "LIKELY_VULNERABLE")
        ]
        out = [
            f"**Endpoints tested:** {total}  |  "
            f"**Confirmed vulnerable:** {len(vulnerable)}\n"
        ]
        if vulnerable:
            out.append("**Vulnerable endpoints:**")
            for v in vulnerable:
                out.append(f"- `{v.get('url', '?')}` — {v.get('finding')} (probe: {v.get('probe', '?')})")
        else:
            out.append("_No missing-authorization issues confirmed on the tested endpoints._")
        return "\n".join(out)

    def _format_password_policy(self, r: dict) -> str:
        if r.get("gap_reason"):
            return f"_Not tested:_ {r['gap_reason']}"

        severity = r.get("severity", {})
        policy = r.get("password_policy", {})
        out = [
            f"**Severity:** {severity.get('label', 'N/A')} (score {severity.get('score', 'N/A')}/100)\n",
            "**Policy settings observed:**",
            f"- Minimum length: {policy.get('minimum_length', 'N/A')}",
            f"- Requires uppercase: {policy.get('requires_uppercase', 'N/A')}",
            f"- Requires lowercase: {policy.get('requires_lowercase', 'N/A')}",
            f"- Requires number: {policy.get('requires_number', 'N/A')}",
            f"- Requires symbol: {policy.get('requires_symbol', 'N/A')}",
            f"- Password history enforced: {policy.get('password_history_enforced', 'N/A')}",
        ]
        findings = severity.get("findings", [])
        if findings:
            out.append("\n**Findings:**")
            for f in findings:
                out.append(f"- {f}")
        return "\n".join(out)

    def _format_mitm(self, r: dict) -> str:
        findings = r.get("findings", [])
        if not findings:
            return "_No findings from the passive observer._"
        out = [f"**{len(findings)} finding(s):**\n"]
        for f in findings:
            # Field names match PassiveHTTPObserver v9.3's real schema —
            # confirmed against an actual report where the previous
            # field names (type/title/indicator) matched nothing in the
            # tool's real output, silently rendering "[High] ?" with
            # Impact/Category/Confidence/Primary URL/Detection Method
            # all dropped even though every one of them was present in
            # the source JSON.
            vuln_type = f.get("vulnerability_type", f.get("type", "?"))
            severity = f.get("severity", "?")
            category = f.get("category")
            confidence = f.get("confidence")
            target_url = f.get("target_url")
            observation = f.get("observation")
            description = f.get("description")
            remediation = f.get("remediation")
            cve = f.get("cve_reference")
            detection_method = (f.get("details") or {}).get("detection_method")

            header = f"- **[{severity}] {vuln_type}**"
            if category:
                header += f" ({category})"
            out.append(header)

            if target_url:
                out.append(f"  - URL: {target_url}")
            if observation:
                out.append(f"  - Observation: {observation}")
            elif description:
                out.append(f"  - Description: {description}")
            if confidence:
                out.append(f"  - Confidence: {confidence}")
            if detection_method:
                out.append(f"  - Detection method: {detection_method}")
            if cve:
                out.append(f"  - CVE: {cve}")
            if remediation:
                out.append(f"  - Remediation: {remediation}")
        return "\n".join(out)

    def _format_sql_family(self, r: dict) -> str:
        summary = r.get("summary", {})
        out = [
            f"**Endpoints tested:** {summary.get('endpoints_tested', 0)}  |  "
            f"**Total tests:** {summary.get('total_tests', summary.get('vulnerabilities_found', 0))}  |  "
            f"**Confirmed:** {summary.get('confirmed', 0)}  |  "
            f"**Possible:** {summary.get('possible', 0)}\n"
        ]
        candidates_routed = summary.get("candidates_routed")
        endpoints_tested = summary.get("endpoints_tested", 0)
        if candidates_routed and candidates_routed > endpoints_tested:
            out.append(
                f"_{candidates_routed} candidate(s) were routed to this agent; "
                f"{endpoints_tested} unique endpoint(s) were actually scanned "
                f"(some candidates pointed at the same real URL):_"
            )
            for url, ids in r.get("endpoint_dedup_map", {}).items():
                if len(ids) > 1:
                    out.append(f"- `{url}` ← {', '.join(str(i) for i in ids)}")
            out.append("")
        findings = r.get("findings", [])
        if findings:
            out.append("**Findings:**")
            for f in findings:
                verdict = f.get("verdict", "?")
                out.append(f"- **[{verdict}]** `{f.get('url', '?')}` — param `{f.get('param', '?')}`")
                out.append(f"  - Payload: `{f.get('payload', '?')}`  |  Confidence: {f.get('confidence', '?')}%")
                if f.get("reason"):
                    out.append(f"  - {f.get('reason')}")
        else:
            out.append("_No confirmed or possible injection found._")
        errors = r.get("_errors", [])
        if errors:
            out.append(f"\n**Errors:** {errors}")
        return "\n".join(out)

    def _format_param_injection(self, r: dict) -> str:
        summary = r.get("summary", {})
        out = [
            f"**Endpoints tested:** {summary.get('endpoints_tested', 0)}  |  "
            f"**Total findings:** {summary.get('total_tests', 0)}  |  "
            f"**Confirmed (High/Critical confidence):** {summary.get('confirmed', 0)}  |  "
            f"**WAF detected:** {summary.get('waf_detected', False)}\n"
        ]
        findings = r.get("findings", [])
        if findings:
            out.append("**Findings:**")
            for f in findings:
                out.append(f"- **[{f.get('confidence', '?')}] {f.get('type', f.get('category', '?'))}** — param `{f.get('param', '?')}` ({f.get('location', '?')})")
                out.append(f"  - Payload: `{f.get('payload', '?')}`")
                if f.get("evidence"):
                    out.append(f"  - Evidence: {f.get('evidence')}")
                if f.get("target"):
                    out.append(f"  - Target: `{f.get('target')}`")
        else:
            out.append("_No findings for the vectors this agent covers "
                        "(SSRF/SSTI/SSPP/Command Injection/Path Traversal/"
                        "Open Redirect/Host Header Injection)._")
        errors = r.get("_errors", [])
        if errors:
            out.append(f"\n**Errors:** {errors}")
        return "\n".join(out)

    def _format_generic(self, r: dict) -> str:
        return f"```json\n{json.dumps(r, indent=2, default=str)[:3000]}\n```"

    _AGENT_FORMATTERS = {
        "XSS_AGENT": _format_xss,
        "AUTHZ_AGENT": _format_authz,
        "PASSWORD_POLICY_AGENT": _format_password_policy,
        "MITM_AGENT": _format_mitm,
        "NOSQL_AGENT": _format_sql_family,
        "SQL_AGENT": _format_sql_family,
        "PARAM_INJECTION_AGENT": _format_param_injection,
    }